apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bigip-metrics

labels:
  - pairs:
      app.kubernetes.io/part-of: bigip-metrics-exporter
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap-otel-collector.yaml
  - configmap-prometheus.yaml
  - rbac-prometheus.yaml
  - deployment-otel-collector.yaml
  - deployment-prometheus.yaml
  - deployment-backend.yaml
  - service-otel-collector.yaml
  - service-prometheus.yaml
  - service-backend.yaml
  - ingress.yaml

images:
  - name: bigip-metrics-exporter
    newName: bigip-metrics-exporter
    newTag: latest
